# Generated by Django 5.2.2 on 2025-06-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresses',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customers',
            options={},
        ),
        migrations.AlterModelOptions(
            name='flaggedorders',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lineitems',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rules',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stores',
            options={},
        ),
    ]
