# Generated by Django 5.2.2 on 2025-06-09 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_addresses_options_alter_customers_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='lineitems',
            name='order_id',
        ),
        migrations.AddField(
            model_name='addresses',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.customers'),
        ),
        migrations.AddField(
            model_name='addresses',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.orders'),
        ),
        migrations.AddField(
            model_name='addresses',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.stores'),
        ),
        migrations.AddField(
            model_name='customers',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.stores'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flaggedorders',
            name='rule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.rules'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineitems',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.customers'),
        ),
        migrations.AddField(
            model_name='orders',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.stores'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rules',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.stores'),
        ),
        migrations.AlterField(
            model_name='lineitems',
            name='remote_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='customers',
            unique_together={('store', 'remote_id')},
        ),
        migrations.AlterUniqueTogether(
            name='orders',
            unique_together={('store', 'remote_id')},
        ),
    ]
