# Generated by Django 5.2.2 on 2025-06-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_addresses_order_id_remove_lineitems_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='remote_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
