# Generated by Django 5.2.2 on 2025-06-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_addresses_remote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='remote_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
