# Generated by Django 5.2.2 on 2025-07-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_addresses_customer_alter_addresses_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('rto', 'RTO'), ('failed', 'Delivery Failed')], default='pending', max_length=20, null=True),
        ),
    ]
